package POJOs;
// Generated 06-sep-2024 21:19:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private Persona persona;
     private Integer horasTrabajo;
     private String dpi;
     private String estadoCivil;
     private BigDecimal sueldo;

    public Empleado() {
    }

    public Empleado(Persona persona, Integer horasTrabajo, String dpi, String estadoCivil, BigDecimal sueldo) {
       this.persona = persona;
       this.horasTrabajo = horasTrabajo;
       this.dpi = dpi;
       this.estadoCivil = estadoCivil;
       this.sueldo = sueldo;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Integer getHorasTrabajo() {
        return this.horasTrabajo;
    }
    
    public void setHorasTrabajo(Integer horasTrabajo) {
        this.horasTrabajo = horasTrabajo;
    }
    public String getDpi() {
        return this.dpi;
    }
    
    public void setDpi(String dpi) {
        this.dpi = dpi;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public BigDecimal getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(BigDecimal sueldo) {
        this.sueldo = sueldo;
    }




}


