package POJOs;
// Generated 29/09/2024 11:15:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Actividades generated by hbm2java
 */
public class Actividades  implements java.io.Serializable {


     private Integer actividadId;
     private Bimestres bimestres;
     private Cursos cursos;
     private String nombreActividad;
     private Set<Notas> notases = new HashSet<Notas>(0);

    public Actividades() {
    }

	
    public Actividades(Bimestres bimestres, Cursos cursos, String nombreActividad) {
        this.bimestres = bimestres;
        this.cursos = cursos;
        this.nombreActividad = nombreActividad;
    }
    public Actividades(Bimestres bimestres, Cursos cursos, String nombreActividad, Set<Notas> notases) {
       this.bimestres = bimestres;
       this.cursos = cursos;
       this.nombreActividad = nombreActividad;
       this.notases = notases;
    }
   
    public Integer getActividadId() {
        return this.actividadId;
    }
    
    public void setActividadId(Integer actividadId) {
        this.actividadId = actividadId;
    }
    public Bimestres getBimestres() {
        return this.bimestres;
    }
    
    public void setBimestres(Bimestres bimestres) {
        this.bimestres = bimestres;
    }
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }
    public String getNombreActividad() {
        return this.nombreActividad;
    }
    
    public void setNombreActividad(String nombreActividad) {
        this.nombreActividad = nombreActividad;
    }
    public Set<Notas> getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set<Notas> notases) {
        this.notases = notases;
    }




}


