package POJOs;
// Generated 10/10/2024 10:33:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bimestres generated by hbm2java
 */
public class Bimestres  implements java.io.Serializable {


     private Integer bimestreId;
     private String nombreBimestre;
     private Set<Evaluaciones> evaluacioneses = new HashSet<Evaluaciones>(0);

    public Bimestres() {
    }

	
    public Bimestres(String nombreBimestre) {
        this.nombreBimestre = nombreBimestre;
    }
    public Bimestres(String nombreBimestre, Set<Evaluaciones> evaluacioneses) {
       this.nombreBimestre = nombreBimestre;
       this.evaluacioneses = evaluacioneses;
    }
   
    public Integer getBimestreId() {
        return this.bimestreId;
    }
    
    public void setBimestreId(Integer bimestreId) {
        this.bimestreId = bimestreId;
    }
    public String getNombreBimestre() {
        return this.nombreBimestre;
    }
    
    public void setNombreBimestre(String nombreBimestre) {
        this.nombreBimestre = nombreBimestre;
    }
    public Set<Evaluaciones> getEvaluacioneses() {
        return this.evaluacioneses;
    }
    
    public void setEvaluacioneses(Set<Evaluaciones> evaluacioneses) {
        this.evaluacioneses = evaluacioneses;
    }




}


