package POJOs;
// Generated 29/09/2024 11:15:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docentes generated by hbm2java
 */
public class Docentes  implements java.io.Serializable {


     private Integer usuarioId;
     private Grados grados;
     private Secciones secciones;
     private String nombreUsuario;
     private String contrasenia;
     private String rol;
     private boolean borradoLogico;
     private Set<Cursos> cursoses = new HashSet<Cursos>(0);

    public Docentes() {
    }

	
    public Docentes(Grados grados, Secciones secciones, String nombreUsuario, String contrasenia, String rol, boolean borradoLogico) {
        this.grados = grados;
        this.secciones = secciones;
        this.nombreUsuario = nombreUsuario;
        this.contrasenia = contrasenia;
        this.rol = rol;
        this.borradoLogico = borradoLogico;
    }
    public Docentes(Grados grados, Secciones secciones, String nombreUsuario, String contrasenia, String rol, boolean borradoLogico, Set<Cursos> cursoses) {
       this.grados = grados;
       this.secciones = secciones;
       this.nombreUsuario = nombreUsuario;
       this.contrasenia = contrasenia;
       this.rol = rol;
       this.borradoLogico = borradoLogico;
       this.cursoses = cursoses;
    }
   
    public Integer getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }
    public Grados getGrados() {
        return this.grados;
    }
    
    public void setGrados(Grados grados) {
        this.grados = grados;
    }
    public Secciones getSecciones() {
        return this.secciones;
    }
    
    public void setSecciones(Secciones secciones) {
        this.secciones = secciones;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public boolean isBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<Cursos> getCursoses() {
        return this.cursoses;
    }
    
    public void setCursoses(Set<Cursos> cursoses) {
        this.cursoses = cursoses;
    }




}


