package POJOs;
// Generated 06-oct-2024 21:01:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiantes generated by hbm2java
 */
public class Estudiantes  implements java.io.Serializable {


     private String cui;
     private Grados grados;
     private Secciones secciones;
     private String codigoPersonal;
     private String nombre;
     private String apellido;
     private boolean borradoLogico;
     private Set<Notas> notases = new HashSet<Notas>(0);

    public Estudiantes() {
    }

	
    public Estudiantes(String cui, Grados grados, Secciones secciones, String codigoPersonal, String nombre, String apellido, boolean borradoLogico) {
        this.cui = cui;
        this.grados = grados;
        this.secciones = secciones;
        this.codigoPersonal = codigoPersonal;
        this.nombre = nombre;
        this.apellido = apellido;
        this.borradoLogico = borradoLogico;
    }
    public Estudiantes(String cui, Grados grados, Secciones secciones, String codigoPersonal, String nombre, String apellido, boolean borradoLogico, Set<Notas> notases) {
       this.cui = cui;
       this.grados = grados;
       this.secciones = secciones;
       this.codigoPersonal = codigoPersonal;
       this.nombre = nombre;
       this.apellido = apellido;
       this.borradoLogico = borradoLogico;
       this.notases = notases;
    }
   
    public String getCui() {
        return this.cui;
    }
    
    public void setCui(String cui) {
        this.cui = cui;
    }
    public Grados getGrados() {
        return this.grados;
    }
    
    public void setGrados(Grados grados) {
        this.grados = grados;
    }
    public Secciones getSecciones() {
        return this.secciones;
    }
    
    public void setSecciones(Secciones secciones) {
        this.secciones = secciones;
    }
    public String getCodigoPersonal() {
        return this.codigoPersonal;
    }
    
    public void setCodigoPersonal(String codigoPersonal) {
        this.codigoPersonal = codigoPersonal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public boolean isBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<Notas> getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set<Notas> notases) {
        this.notases = notases;
    }




}


