package POJOs;
// Generated 29/09/2024 11:15:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Evaluaciones generated by hbm2java
 */
public class Evaluaciones  implements java.io.Serializable {


     private Integer evaluacionId;
     private Bimestres bimestres;
     private Cursos cursos;
     private String nombreEvaluacion;
     private Set<Notas> notases = new HashSet<Notas>(0);

    public Evaluaciones() {
    }

	
    public Evaluaciones(Bimestres bimestres, Cursos cursos, String nombreEvaluacion) {
        this.bimestres = bimestres;
        this.cursos = cursos;
        this.nombreEvaluacion = nombreEvaluacion;
    }
    public Evaluaciones(Bimestres bimestres, Cursos cursos, String nombreEvaluacion, Set<Notas> notases) {
       this.bimestres = bimestres;
       this.cursos = cursos;
       this.nombreEvaluacion = nombreEvaluacion;
       this.notases = notases;
    }
   
    public Integer getEvaluacionId() {
        return this.evaluacionId;
    }
    
    public void setEvaluacionId(Integer evaluacionId) {
        this.evaluacionId = evaluacionId;
    }
    public Bimestres getBimestres() {
        return this.bimestres;
    }
    
    public void setBimestres(Bimestres bimestres) {
        this.bimestres = bimestres;
    }
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }
    public String getNombreEvaluacion() {
        return this.nombreEvaluacion;
    }
    
    public void setNombreEvaluacion(String nombreEvaluacion) {
        this.nombreEvaluacion = nombreEvaluacion;
    }
    public Set<Notas> getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set<Notas> notases) {
        this.notases = notases;
    }




}


