package POJOs;
// Generated 10/10/2024 10:33:56 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Notas generated by hbm2java
 */
public class Notas  implements java.io.Serializable {


     private Integer notaId;
     private Estudiantes estudiantes;
     private Evaluaciones evaluaciones;
     private BigDecimal nota;

    public Notas() {
    }

    public Notas(Estudiantes estudiantes, Evaluaciones evaluaciones, BigDecimal nota) {
       this.estudiantes = estudiantes;
       this.evaluaciones = evaluaciones;
       this.nota = nota;
    }
   
    public Integer getNotaId() {
        return this.notaId;
    }
    
    public void setNotaId(Integer notaId) {
        this.notaId = notaId;
    }
    public Estudiantes getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Estudiantes estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Evaluaciones getEvaluaciones() {
        return this.evaluaciones;
    }
    
    public void setEvaluaciones(Evaluaciones evaluaciones) {
        this.evaluaciones = evaluaciones;
    }
    public BigDecimal getNota() {
        return this.nota;
    }
    
    public void setNota(BigDecimal nota) {
        this.nota = nota;
    }




}


