package POJOs;
// Generated 29/09/2024 11:15:42 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Notas generated by hbm2java
 */
public class Notas  implements java.io.Serializable {


     private int notaId;
     private Actividades actividades;
     private Estudiantes estudiantes;
     private Evaluaciones evaluaciones;
     private BigDecimal nota;

    public Notas() {
    }

	
    public Notas(int notaId, Estudiantes estudiantes, BigDecimal nota) {
        this.notaId = notaId;
        this.estudiantes = estudiantes;
        this.nota = nota;
    }
    public Notas(int notaId, Actividades actividades, Estudiantes estudiantes, Evaluaciones evaluaciones, BigDecimal nota) {
       this.notaId = notaId;
       this.actividades = actividades;
       this.estudiantes = estudiantes;
       this.evaluaciones = evaluaciones;
       this.nota = nota;
    }
   
    public int getNotaId() {
        return this.notaId;
    }
    
    public void setNotaId(int notaId) {
        this.notaId = notaId;
    }
    public Actividades getActividades() {
        return this.actividades;
    }
    
    public void setActividades(Actividades actividades) {
        this.actividades = actividades;
    }
    public Estudiantes getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Estudiantes estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Evaluaciones getEvaluaciones() {
        return this.evaluaciones;
    }
    
    public void setEvaluaciones(Evaluaciones evaluaciones) {
        this.evaluaciones = evaluaciones;
    }
    public BigDecimal getNota() {
        return this.nota;
    }
    
    public void setNota(BigDecimal nota) {
        this.nota = nota;
    }




}


