package POJOs;
// Generated 02-oct-2024 21:21:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Secciones generated by hbm2java
 */
public class Secciones  implements java.io.Serializable {


     private Integer seccionId;
     private String nombreSeccion;
     private Set<Evaluaciones> evaluacioneses = new HashSet<Evaluaciones>(0);
     private Set<Docentes> docenteses = new HashSet<Docentes>(0);
     private Set<Estudiantes> estudianteses = new HashSet<Estudiantes>(0);

    public Secciones() {
    }

	
    public Secciones(String nombreSeccion) {
        this.nombreSeccion = nombreSeccion;
    }
    public Secciones(String nombreSeccion, Set<Evaluaciones> evaluacioneses, Set<Docentes> docenteses, Set<Estudiantes> estudianteses) {
       this.nombreSeccion = nombreSeccion;
       this.evaluacioneses = evaluacioneses;
       this.docenteses = docenteses;
       this.estudianteses = estudianteses;
    }
   
    public Integer getSeccionId() {
        return this.seccionId;
    }
    
    public void setSeccionId(Integer seccionId) {
        this.seccionId = seccionId;
    }
    public String getNombreSeccion() {
        return this.nombreSeccion;
    }
    
    public void setNombreSeccion(String nombreSeccion) {
        this.nombreSeccion = nombreSeccion;
    }
    public Set<Evaluaciones> getEvaluacioneses() {
        return this.evaluacioneses;
    }
    
    public void setEvaluacioneses(Set<Evaluaciones> evaluacioneses) {
        this.evaluacioneses = evaluacioneses;
    }
    public Set<Docentes> getDocenteses() {
        return this.docenteses;
    }
    
    public void setDocenteses(Set<Docentes> docenteses) {
        this.docenteses = docenteses;
    }
    public Set<Estudiantes> getEstudianteses() {
        return this.estudianteses;
    }
    
    public void setEstudianteses(Set<Estudiantes> estudianteses) {
        this.estudianteses = estudianteses;
    }




}


